language: node_js

node_js:
  - node
  - 12
  - 11

install: npm ci

cache:
  directories:
  - "$HOME/.npm"

env:
  - NODE_ENV=travis

before_install:
  - npm install -g typescript coveralls codacy-coverage

script: npm test -- --coverage

after_success:
  - cat ./coverage/lcov.info | coveralls
  - cat ./coverage/lcov.info | codacy-coverage
  - bash <(curl -s https://codecov.io/bash) 